const express = require('express');
const fs = require('fs');
const multer = require('multer');
const upload = multer(); // setting the default
const bodyParser = require('body-parser');

const cors = require('cors');
const app = express();
app.use(cors())
// app.use(express.json());
// app.use(express.urlencoded({ extended: false }));
app.use(upload.array())


app.use(bodyParser.json({ limit: '50mb' }));
app.use(bodyParser.urlencoded({ extended: true, limit: '50mb' }));
// app.use(express.static('public'))



let counter = 0;

app.post('/upload', (req, res, data) => {

    //below code will read the data from the upload folder. Multer will automatically upload the file in that folder with an autogenerated name
    const {
        base64dataImages
    } = req.body;


    base64dataImages.map((base64data) => {
        let b64d;
        // console.log(base64data.charAt(9))
        const imageFormat = base64data.substring("data:image/".length, base64data.indexOf(";base64"))
        switch (imageFormat) {
            case "png":
                b64d = base64data.replace(/^data:image\/png;base64,/, "");
                break;
            case "jpg":
                b64d = base64data.replace(/^data:image\/jpg;base64,/, "");
                break;
            case "jpeg":
                b64d = base64data.replace(/^data:image\/jpeg;base64,/, "");
                break;
            case "webp":
                b64d = base64data.replace(/^data:image\/webp;base64,/, "");
                break;
            default:
        }

        fs.writeFile(`out${counter}.${imageFormat}`, b64d, 'base64', function (err) {

        })
        counter++;
    })


});


// app.get('/getImage', (req, res) => {
//     res.json(imageData);
//     console.log('sent');
// })








app.listen(5000, () => {
    console.log(`App is listening on 5000`);
})