const express = require('express');
const fs = require('fs');
const multer = require('multer');
const upload = multer(); // setting the default
const bodyParser = require('body-parser');

const cors = require('cors');
const app = express();
app.use(cors())
// app.use(express.json());
// app.use(express.urlencoded({ extended: false }));
app.use(upload.array())


app.use(bodyParser.json({ limit: '50mb' }));
app.use(bodyParser.urlencoded({ extended: true, limit: '50mb' }));
// app.use(express.static('public'))



let counter = 0;

app.post('/upload', (req, res, data) => {

    //below code will read the data from the upload folder. Multer will automatically upload the file in that folder with an autogenerated name
    const {
        base64dataImages
    } = req.body;


    base64dataImages.map((base64data) => {
        let b64d;
        // console.log(base64data.charAt(9))
        const imageFormat = base64data.substring("data:image/".length, base64data.indexOf(";base64"))
        switch (imageFormat) {
            case "png":
                b64d = base64data.replace(/^data:image\/png;base64,/, "");
                break;
            case "jpg":
                b64d = base64data.replace(/^data:image\/jpg;base64,/, "");
                break;
            case "jpeg":
                b64d = base64data.replace(/^data:image\/jpeg;base64,/, "");
                break;
            case "webp":
                b64d = base64data.replace(/^data:image\/webp;base64,/, "");
                break;
            default:
        }

        fs.writeFile(`out${counter}.${imageFormat}`, b64d, 'base64', function (err) {

        })
        counter++;
    })


});

const past_res = [];
app.get('/past_reservations', (req, res) => {
    res.json(past_res);
});

app.post('/book', (req, res) => {
    const {
        reservation
    } = req.body;
    console.log('reservation ', reservation);
    past_res.push(reservation);
    res.json({ msg: 'Booked successfully' });
});


app.get('/sport_locations', (req, res) => {

    const data = [{
        images: ['i1.jpg', 'i2.jpg'],
        title: 'Coolest Basketball Place',
        location: 'Bucharest, Sector 5',
        sport: 'Basketball',
        format: '40x70m',
        type: 'Indoor',
        surface: 'Grass',
        min_zone_part: '1/2 zone',
        price: '50$ / 30min',
        serviceOptions: ['1 court 60min,41$', '1 court 30min,41$', '1 court 90min,41$', '1 court 120min,41$'],
        availableTimes: ['08:00', '09:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00']
    },
    {
        images: ['i1.jpg', 'i2.jpg'],
        title: 'Coolest Basketball Place',
        location: 'Bucharest, Sector 5',
        sport: 'Basketball',
        format: '40x70m',
        type: 'Indoor',
        surface: 'Grass',
        min_zone_part: '1/2 zone',
        price: '50$ / 30min',
        serviceOptions: ['1 court 60min,41$', '1 court 30min,41$', '1 court 90min,41$', '1 court 120min,41$'],
        availableTimes: ['08:00', '09:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00']
    },
    {
        images: ['i1.jpg', 'i2.jpg'],
        title: 'Coolest Basketball Place',
        location: 'Bucharest, Sector 5',
        sport: 'Basketball',
        format: '40x70m',
        type: 'Indoor',
        surface: 'Grass',
        min_zone_part: '1/2 zone',
        price: '50$ / 30min',
        serviceOptions: ['1 court 60min,41$', '1 court 30min,41$', '1 court 90min,41$', '1 court 120min,41$'],
        availableTimes: ['08:00', '09:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00']
    },
    {
        images: ['i1.jpg', 'i2.jpg'],
        title: 'Coolest Basketball Place',
        location: 'Bucharest, Sector 5',
        sport: 'Basketball',
        format: '40x70m',
        type: 'Indoor',
        surface: 'Grass',
        min_zone_part: '1/2 zone',
        price: '50$ / 30min',
        serviceOptions: ['1 court 60min,41$', '1 court 30min,41$', '1 court 90min,41$', '1 court 120min,41$'],
        availableTimes: ['08:00', '09:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00']
    }, {
        images: ['i1.jpg', 'i2.jpg'],
        title: 'Coolest Basketball Place',
        location: 'Bucharest, Sector 5',
        sport: 'Basketball',
        format: '40x70m',
        type: 'Indoor',
        surface: 'Grass',
        min_zone_part: '1/2 zone',
        price: '50$ / 30min',
        serviceOptions: ['1 court 60min,41$', '1 court 30min,41$', '1 court 90min,41$', '1 court 120min,41$'],
        availableTimes: ['08:00', '09:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00']
    }, {
        images: ['i1.jpg', 'i2.jpg'],
        title: 'Coolest Basketball Place',
        location: 'Bucharest, Sector 5',
        sport: 'Basketball',
        format: '40x70m',
        type: 'Indoor',
        surface: 'Grass',
        min_zone_part: '1/2 zone',
        price: '50$ / 30min',
        serviceOptions: ['1 court 60min,41$', '1 court 30min,41$', '1 court 90min,41$', '1 court 120min,41$'],
        availableTimes: ['08:00', '09:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00']
    }, {
        images: ['i1.jpg', 'i2.jpg'],
        title: 'Coolest Basketball Place',
        location: 'Bucharest, Sector 5',
        sport: 'Basketball',
        format: '40x70m',
        type: 'Indoor',
        surface: 'Grass',
        min_zone_part: '1/2 zone',
        price: '50$ / 30min',
        serviceOptions: ['1 court 60min,41$', '1 court 30min,41$', '1 court 90min,41$', '1 court 120min,41$'],
        availableTimes: ['08:00', '09:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00']
    }, {
        images: ['i1.jpg', 'i2.jpg'],
        title: 'Coolest Basketball Place',
        location: 'Bucharest, Sector 5',
        sport: 'Basketball',
        format: '40x70m',
        type: 'Indoor',
        surface: 'Grass',
        min_zone_part: '1/2 zone',
        price: '50$ / 30min',
        serviceOptions: ['1 court 60min,41$', '1 court 30min,41$', '1 court 90min,41$', '1 court 120min,41$'],
        availableTimes: ['08:00', '09:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00']
    }, {
        images: ['i1.jpg', 'i2.jpg'],
        title: 'Coolest Basketball Place',
        location: 'Bucharest, Sector 5',
        sport: 'Basketball',
        format: '40x70m',
        type: 'Indoor',
        surface: 'Grass',
        min_zone_part: '1/2 zone',
        price: '50$ / 30min',
        serviceOptions: ['1 court 60min,41$', '1 court 30min,41$', '1 court 90min,41$', '1 court 120min,41$'],
        availableTimes: ['08:00', '09:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00']
    }]
    res.json(data);
})

app.get('/messages', (req, res) => {
    res.json({ messages: ['title 1', 'title 2', 'title 3', 'title 4', 'title 5'] })
})


const users = [];

app.post('/register', (req, res) => {
    const {
        data
    } = req.body;
    console.log(data);
    users.push(data);
    res.json('register success');
});

app.post('/login', (req, res) => {
    const {
        data
    } = req.body;
    let userExists = false;
    users.map((user) => {
        if (data.username) {
            if (data.username === user.username && data.password === user.password)
                userExists = true;
        }
        if (data.email) {
            if (data.email === user.email && data.password === user.password)
                userExists = true;
        }
    });

    res.json(userExists);
})





app.listen(5000, () => {
    console.log(`App is listening on 5000`);
})